apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-api-21746
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/gateway-api-21746
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
